FROM node:20

WORKDIR /app

RUN mkdir -p /opt/node_deps/node_modules

COPY package.json package-lock.json /opt/node_deps/

RUN npm install --prefix /opt/node_deps
ENV NODE_PATH=/opt/node_deps/node_modules
ENV PATH=$PATH:/opt/node_deps/node_modules/.bin

CMD ["npm", "run", "dev", "--", "--host"]
